### ISSUE TITLE
General Resistance Desktop Bug Fixes

### ISSUE THREAD

**Issue by lukewegryn** [ResistancePlatform/grants#1]
This is a proposal for bug fixes to the Resistance Desktop wallet. If this proposal is approved by the Masternode voters, then the developers that fix these bugs will be issued a grant from the developer's fund (from the 10% reward splitting).

The first fix that will receive RES reward from development fund:
- Removing Child Process Error bug (61,800 RES)

A simple majority will be used to approve or reject this proposal. At least one Masternode must vote on an issue for it to be approved. To apply with a proposal email admin [at] resistance.io and include your GitHub username in your email so our admins can verify your development record. For information on how to cast your vote, please refer to the README in this repository.

**Comment by whiteknightrader** [comment]
-----BEGIN VOTE-----
Y:1:r17bxNVqW8o2BmXy6CEZnkDDyXcTHFWyQbB:1588770927:H862KDRX2Wq+2Ax+cXo3IwplmL8T/X3CT9aw/fu/P/IBMXDgOrGT42qROErktDgkwA5ph6Cw++BYMRDzJqKfoXY=
-----END VOTE-----

**Comment by juaol** [comment]
I put in putty into my MN
/bin/bash -c “$(curl -fsSL https://raw.githubusercontent.com/ResistancePlatform/grants/master/vote.sh)"
and it gave an error
How did you do it?

**Comment by juaol** [comment]
Hi 
I tried to add the command in my MN through Putty 
/bin/bash -c “$(curl -fsSL https://raw.githubusercontent.com/ResistancePlatform/grants/master/vote.sh)"

but it does not prompt me any options. It only shows >
how did you do it?
thanks
Juanjo

**Comment by ghost** [comment]
-----BEGIN VOTE-----
Y:1:r13fwb1K9sK6YYoTf22c6CJPxequKMxcA7L:1588955678:INeb9Dz0UePIdmhaa8WBSfjw5NUHsrWfBpqDbPro4tGYQe0q+kO4jdWPvaPkkgEj+Lv9Z1KZw1/LnG/bLJVOUyo=
-----END VOTE-----

**Comment by ghost** [comment]
We have a dev to take care of this first grant. 
We have a small group of devs and one of them is willing to start but we need better communition. this group is 6 people. Can you please Luke join this group and we can move things faster?

**Comment by ghost** [comment]
Luke this is done over a week ago!  Come on! We are keen to work and take the grant! We have also proposed a dev and we have 2 more! We wat just for you. Thanks

**Comment by lukewegryn** [comment]
The votes have been tallied and the results are in favor of accepting this proposal.

```
cat list_of_votes.txt
-----BEGIN VOTE-----
Y:1:r17bxNVqW8o2BmXy6CEZnkDDyXcTHFWyQbB:1588770927:H862KDRX2Wq+2Ax+cXo3IwplmL8T/X3CT9aw/fu/P/IBMXDgOrGT42qROErktDgkwA5ph6Cw++BYMRDzJqKfoXY=
-----END VOTE-----
-----BEGIN VOTE-----
Y:1:r13fwb1K9sK6YYoTf22c6CJPxequKMxcA7L:1588955678:INeb9Dz0UePIdmhaa8WBSfjw5NUHsrWfBpqDbPro4tGYQe0q+kO4jdWPvaPkkgEj+Lv9Z1KZw1/LnG/bLJVOUyo=
-----END VOTE-----

```

```

cat list_of_votes.txt | grep -v "BEGIN VOTE" | grep -v "END VOTE" | ./verify.sh 1

--------------------------------------------------------
| Final Tally for GitHub Issue: 1
--------------------------------------------------------
| YES: 2
|-------------------------------------------------------
| NO: 0
--------------------------------------------------------
```

This grant is approved. Once the terms of the proposal are met, we will release the RES reward from the dev fund.

**Comment by whiteknightrader** [comment]
@lukewegryn Hi. i have resolved the issue. Kindly consider closing this grant

**Comment by ghost** [comment]
Luke, please let us know how will this me announce to the community .  It is important they see the efforts and improvements asap. Also, please announce grant 2 and 3 as discussed by the team group in discord . Talk to Alexander when possible. Thanks!
The grant please pay it fully to ranjith. Thank you

**Comment by ian-p-johnson** [comment]
What was the bug (Removing Child Process Error bug ? )
What was the solution ?
When will it be released ?

**Comment by ghost** [comment]
@ian-p-johnson the solution was fully detailed in resistance community group and I personally sent it to you.
So, you can share with the other community. 
Please note that this was the solution to resolved the child-process-error related to 2.2.9 installation . Thanks . Juanjo

**Comment by ian-p-johnson** [comment]
Please include a summary here - there are some interesting details pertaining to the original release "minerd of windows in 2.2.9 release is 0 byte" - which really says it all !

**Comment by lukewegryn** [comment]
Grant completed and RES sent to developer
