### ISSUE TITLE
Grant #8 - To complete the Desktop version of the Resistance Wallet for Linux

### ISSUE THREAD

**Issue by ghost** [ResistancePlatform/grants#8]
**Grant 8:**
This is a proposal for a Resistance Support task:
An experienced Linux developer is required to complete the CLI version of the Resistance Wallet.
If this proposal is approved by the Masternode voters, then the community member who performs this task will be issued a grant from the developer's fund (from the 10% reward splitting).
**The amount of RES granted will be: 108,697**
A simple majority will be used to approve or reject this proposal. At least one Masternode must vote on an issue for it to be approved. To apply with a proposal email admin [at] resistance.io and include your GitHub username in your email so our admins can verify your development record. For information on how to cast your vote, please refer to the README in this repository.
**Voting opens immediately and will close on: 22nd July 2020, developers have until 1st August to send in proposals if the grant is approved.**

**Comment by ghost** [comment]
-----BEGIN VOTE-----
Y:8:r13fwb1K9sK6YYoTf22c6CJPxequKMxcA7L:1594661588:IEq4guEOCvhfdP5iBwUFZugHFrdcN7P5+aAg3rggPBCiJ6iLFDJkIvntMYbZo2itVGtc7Dx3mwEUiwdjRiqEZRY=
-----END VOTE-----

**Comment by MEtoolel** [comment]
Y:8:r18fiaRwkHZNy2n37wRLrH4SuFTfJJCS2HV:1594695817:H0ztm8m+2KocDB9NUSR3T7ratyK1qex3UQDR36R3z9J6XFhy2q5IcWNYMKrxx5OzUrj6rOCXs9cD3HUhtOHtr1k=

**Comment by whiteknightrader** [comment]
-----BEGIN VOTE-----
Y:8:r1B5YJxB8CGjmmXhBtEmAZd25QdvKEGNgxq:1594751856:INrXTUnwoPX/e5k4S6XDtlSHw/kom1dDHb4cSDxIHwBUckiS8IJCjK/m9C2DaqMl0SxYZQrrj90I6kCfBsCIyrY=
-----END VOTE-----

**Comment by ian-p-johnson** [comment]
I don't understand - there is already a command line for the wallet - although one has not been released as a windows binary you can still build it.  Can you say what this wallet is to do that it cannot do already - you can send assets, receive assets, list assets - what more are you planning to add?

**Comment by ghost** [comment]
> I don't understand - there is already a command line for the wallet - although one has not been released as a windows binary you can still build it. Can you say what this wallet is to do that it cannot do already - you can send assets, receive assets, list assets - what more are you planning to add?

Ian, the grant is to make a GUI Linux wallet. So the whole Resistance wallet as it is downloaded today in MacOS or in Windows as an .exe file will also be available as a .deb file and will include all the features as the windows version including the RESdex. So, it will be a fully operationaal Resistance wallet but for Linux users.

**Comment by solardiz** [comment]
@ian-p-johnson I also don't understand. As I wrote to others on the team a couple of days ago:

I don't understand what is meant by "complete the CLI version of the Resistance Wallet". Is there a description of this task anywhere? My best guess is it's related to "CLI Wallet (coming soon)" on the Resistance website, which is a system-specific packaging and ongoing maintenance task.

@juaol No, this grant's description specifically says CLI, not GUI.

I think the team needs to specify this grant more fully before it can be considered for real. Hopefully, soon.

**Comment by ghost** [comment]
I do not think that will happen Ian. My description should be enough. In fact, it was me who published it. So, it is clear the task, a Linux version of Resistance as we have a windows and a MacOS version.

**Comment by ian-p-johnson** [comment]
-----BEGIN VOTE-----
Y:8:r11GEr8jrS3SBGSdZ7F2Msfg8fUbTo8U7RH:1594842867:H0dJV3e+iafCT6ob7UAoYV2ruV3fD3ffniJMyUsLxR8qJq1KmrptOEaWDTOE1yR5HTwVFf0KOCyXIwVVNkpl/NE=
-----END VOTE-----

**Comment by ghost** [comment]
> @ian-p-johnson I also don't understand. As I wrote to others on the team a couple of days ago:
> 
> 
> 
> I don't understand what is meant by "complete the CLI version of the Resistance Wallet". Is there a description of this task anywhere? My best guess is it's related to "CLI Wallet (coming soon)" on the Resistance website, which is a system-specific packaging and ongoing maintenance task.
> 
> 
> 
> @juaol No, this grant's description specifically says CLI, not GUI.
> 
> 
> 
> I think the team needs to specify this grant more fully before it can be considered for real. Hopefully, soon.

The person to fully clarify this is Luke and he is suppose to be on holidays and we are already trying to get in contact with him to fix the MN. So he will clarify this but ASAP lo

**Comment by ian-p-johnson** [comment]
I don't have access to edit this grant and cannot without agreement. It looks like you took the term CLI Wallet from the Resistance website installation guide when it mentioned "CLI Wallet (coming soon)" with apt, choco, brew installers. Assuming you do indeed mean a GUI wallet then it requires a build of all software FROM SOURCE

A better description would be 
Title: "Build a deployable GUI wallet for Linux "
Description: "Build a deployable GUI wallet for at least one major Linux platform (say Debian/Ubuntu) using the existing GUI Electron cross platform framework code. Build a binary resdex, resistance core, miner (optional ?) and cli

This will of course need access to sources for:
1. RESDEX server component (sources not yet released)
2. The wallet GUI (written in electron) (sources not yet public)
3. (miner, core, cli have already been released for Linux )

I am also assuming a Mac version is not a requirement per website


GUI is Graphical User Interface 
CLI is a COMMAND LINE INTERFACE (with NO GUI) and would conventionally be a set of tools to access the wallet balances, transfer assets etc FROM THE command line. The core already comes with such a CLI for wallet operations but a build was NOT RELEASED for Windows. The DEX is another matter - there is NO SUCH CLI interface to the DEX and i would question the need for one

**Comment by ghost** [comment]
Ian the grants are still described by Luke (resistance team) I just post them as I receive them and I assign them and approve them . I cannot change the grant without Luke’s approval

**Comment by ghost** [comment]
@lukewegryn Please see comment above . Can you please comment?

**Comment by lukewegryn** [comment]
Hey guys, yes this was very confusing. This was meant to be "To complete the Desktop version of the Resistance Wallet for Linux". Right now we only support and package the Mac and Linux Desktop wallet, but we should also support Linux as well. It basically already runs on Linux, but there are a few issues with HTML/JS which make the wallet look funny. We also need to test the functionality of all of the different components (Tor for example) in the Linux wallet to make sure it works as expected. 

I have changed the title of this issue to reflect the update. Do you think we need to do another vote now that the title has changed?

**Comment by ghost** [comment]
No, Luke. No need for more voting but
1/ it has to be clear what is expected as what Ian is asking is different and my idea was closer to make resistance software exactly the same in Linux 
2/. Consider if we break it down in several grants 
3/ I would like @whiteknightrader to give his opinion 
Thanks
Juanjo

**Comment by ghost** [comment]
And I would suggest to do grant 4 and 5 first . 7 is also very good one. Step by step 
Also we need to start working on the resdex more in detail. We also hace the list of 14 points from konstantin

**Comment by whiteknightrader** [comment]
@lukewegryn consider my vote include for the title change too. 

@juaol no issues, we will test Linux desktop wallet for its functions and release.

**Comment by ghost** [comment]
Great @whiteknightrader i fully support you.

**Comment by ghost** [comment]
My vote is also good for new title . @lukewegryn

**Comment by hamiltonga** [comment]
-----BEGIN VOTE-----
Y:8:r18Dsyhhr6GcQJp8SxGqbtYZNCDaxm8DuN6:1595418785:IMdVra9BxVgcWqZg4CL9lHW1qDz3ktIZCjPvhOaNJrPSAcYjqkz3f8xiQM9WQp1/OUvbRl9t0TUAG25392Spx7I=
-----END VOTE-----

**Comment by ghost** [comment]
The votes have been tallied and the results are in favor of accepting this proposal.

cat list_of_votes8.txt
-----BEGIN VOTE-----
Y:8:r13fwb1K9sK6YYoTf22c6CJPxequKMxcA7L:1594661588:IEq4guEOCvhfdP5iBwUFZugHFrdcN7P5+aAg3rggPBCiJ6iLFDJkIvntMYbZo2itVGtc7Dx3mwEUiwdjRiqEZRY=
-----END VOTE-----
-----BEGIN VOTE-----
Y:8:r1B5YJxB8CGjmmXhBtEmAZd25QdvKEGNgxq:1594751856:INrXTUnwoPX/e5k4S6XDtlSHw/kom1dDHb4cSDxIHwBUckiS8IJCjK/m9C2DaqMl0SxYZQrrj90I6kCfBsCIyrY=
-----END VOTE-----
-----BEGIN VOTE-----
Y:8:r18fiaRwkHZNy2n37wRLrH4SuFTfJJCS2HV:1594695817:H0ztm8m+2KocDB9NUSR3T7ratyK1qex3UQDR36R3z9J6XFhy2q5IcWNYMKrxx5OzUrj6rOCXs9cD3HUhtOHtr1k=
-----END VOTE-----
-----BEGIN VOTE-----
Y:8:r11GEr8jrS3SBGSdZ7F2Msfg8fUbTo8U7RH:1594842867:H0dJV3e+iafCT6ob7UAoYV2ruV3fD3ffniJMyUsLxR8qJq1KmrptOEaWDTOE1yR5HTwVFf0KOCyXIwVVNkpl/NE=
-----END VOTE-----
-----BEGIN VOTE-----
Y:8:r18Dsyhhr6GcQJp8SxGqbtYZNCDaxm8DuN6:1595418785:IMdVra9BxVgcWqZg4CL9lHW1qDz3ktIZCjPvhOaNJrPSAcYjqkz3f8xiQM9WQp1/OUvbRl9t0TUAG25392Spx7I=
-----END VOTE-----

 tr -d '\r' < list_of_votes8.txt | grep -v "BEGIN VOTE"                                                                                                                                                | grep -v "END VOTE" | ./verify.sh 8
jq installed... proceeding
curl installed... proceeding

--------------------------------------------------------
| Final Tally for GitHub Issue: 8
--------------------------------------------------------
| YES: 5
|-------------------------------------------------------
| NO: 0
--------------------------------------------------------

This grant is **approved**. 
**Developers have until 1st August to send in proposals**
The amount of RES granted will be: **108,697 RES**
Once the terms of the proposal are met, we will release the RES reward from the dev fund
Look forward to your proposals
Thank you!

**Comment by whiteknightrader** [comment]
I will try this grant.

**Comment by ghost** [comment]
> I will try this grant.

You have just been Assigned @whiteknightrader to complete this task. Good luck

**Comment by ian-p-johnson** [comment]
Just to clarify - must the grant be COMPLETED before the award is released - what does "terms of the proposal are met" exactly mean ? The same goes for the other grants

**Comment by ghost** [comment]
Terms of proposal are clear on the grant. Your question is answered in the other grant. If what you aim is to see the code to fork it and so on... I think Ian you may have to wait. Team will decide if work is done and check it and once release community will make any necessary comments if something goes wrong. you keep on calling this project dead , scam, etc but you show a very high degree of interest for the work we do 🤔🤔🤔

**Comment by ian-p-johnson** [comment]
The team cannot be trusted to "decide if work is done and check" else they would have done it themselves in the first place - it should be pushed out for the community to test/verify, feed back on - it needn't be perfect but it should be verifiably what was specified 

My fear is that we will see a claim that it is done with no evidence .. and then tick a box

**Comment by ghost** [comment]
First of all, I trust both some members of the team and above our community dev. Secondly, would it really be bad for us that the “box are ticked” and we really move into full decentralisation ?   I personally cannot wait....it is the only way to make this project a success . So PLEASE tick boxes, they guys that consider that boxes were not ticked and it was a scam they always have the legal path . I personally want to see this project succeed, move faster and get rid of all the bad things around it = fully decentralisation. So please let them tick the boxes and let us manage the project before there are boxes to be ticked . We are anyway doing most of the work already despite all the lack of gratitude and obstacles

**Comment by whiteknightrader** [comment]
Kindly mark this issue as closed. Resistance wallet for Linux has been released.
